name = "AssignmentProblem"
uuid = "dc172be3-76df-4d74-9af2-4db5b01c6f70"
authors = ["Lior Sinai <sinailior@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
